fix #465 #451 extra param for withdraw, inevm table abi
eosnetworkfoundation/eos-evm pull request #521
Opened 2023-05-08 06:41 UTC by taokayan

Resolve #465 #451

2023-05-10 01:07 UTC, arhag requested changes
Please add a test that uses the new withdraw feature to withdraw to a separate account. Also add a test to ensure we can withdraw from the eosio.evm balance.

2023-05-10 01:10 UTC, arhag commented
I'm not seeing the `inevm` table show up in the generated ABI still.

2023-05-16 07:39 UTC, taokayan commented
please review test cases @arhag . thank you!

2023-05-17 01:34 UTC, arhag approved these changes

2023-05-17 03:38 UTC, merged