Remove SSH URL for git submodules
eosnetworkfoundation/eos-evm pull request #564
Opened 2023-05-29 19:10 UTC by Johnaverse

Sample fixing for Resolves #523 
- Removing SSH URL from .gitmodules
+ Add HTTPS URL in .gitmodules

2023-05-30 21:16 UTC, kj4ezj requested changes
The dockerfile is unrelated to the stated purpose of the PR, and also does not follow standard dockerfile conventions.

2023-05-30 22:10 UTC, Johnaverse commented
Sorry for my mistake. Just removed the Dockerfile for this PR

2023-05-30 23:11 UTC, spoonincode approved these changes

2023-05-31 00:00 UTC, kj4ezj approved these changes
Note that [Tool Install Guide](https://github.com/eosnetworkfoundation/engineering/blob/143c3bf9038069bb9cea249cd58e5cc968b7b458/tooling/tool-install-guide.md) section `16` > `vi` > `f` contains instructions to force `git` to use SSH to clone submodules defined in HTTPS, which is usually desirable for developers.

2023-05-31 00:03 UTC, merged